apiVersion: apps/v1
kind: Deployment ## kind is Deployment
metadata: # Deployement information
    name: nginx-deployment # deployment name
    labels:
        app: nginx
spec: # specification for deployment
    replicas: 2
    selector:
        matchLabels:
            app: nginx 
    template:
        metadata:
            labels:
                app: nginx
        spec:  # specification for pod
            containers:
            - name: nginx
              image: nginx:1.16
              ports:
              - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata: 
  name: nginx-service
spec:
  selector:
      app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080